name: Run Tests
on:
  push:
    branches:
      - main
    paths:
      - "makefile"
      - "**/*.c"
      - "**/*.h"
  workflow_dispatch:
    
      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: mkdir build && make test