name: Run Tests
on:
  push:
    branches:
      - main
    paths:
      - "makefile"
      - "**/*.c"
      - "**/*.h"
  workflow_dispatch:
    
      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Making build directory
      run: mkdir build

    - name: Run lexer tests
      run: make test-lexer

    - name: Run parser tests
      run: bash tests/e2e-test.sh